kind: pipeline
type: docker
name: 米游社签到
steps:
node:
  server: USA
clone:
  disable: true
steps:
- name: 初始化环境
  image: chaikair/dockeri:latest
  volumes:
  - name: cache
    path: /mi
  - name: docker-sock
    path: /var/run/docker.sock
  commands:
  - docker stop mihoyobbsv1
  - docker rm mihoyobbsv1
  - docker image prune -f
  - docker volume prune -f
# 初始化
- name: 自动构建
  image: chaikair/dockeri:latest
  volumes:
  - name: cache
    path: /mi
  - name: docker-sock
    path: /var/run/docker.sock
  commands:
  - apk add git
  - cd /mi
  - git clone https://github.com/qpzxcv4869/AutoMihoyoBBS
  - cd Auto*
  - docker build -t chaikair/test:1 .
# 部署
- name: 自动部署
  image: chaikair/dockeri:latest
  volumes:
  - name: docker-sock
    path: /var/run/docker.sock
  commands:
  - docker run --name mihoyobbsv1 -d --restart=always chaikair/test:1
# 清理
- name: 上传镜像
  image: chaikair/dockeri:latest
  volumes:
  - name: docker-sock
    path: /var/run/docker.sock
  commands:
  - docker login --username=chaikair --password=389609066
  - docker push chaikair/test:1
# 声明储存
volumes:
- name: cache
  temp: {}
- name: docker-sock
  host:
   path: /var/run/docker.sock
