kind: pipeline
type: docker
name: 米游社签到
steps:
node:
  server: USA
clone:
  disable: true
steps:
- name: 自动构建
  image: chaikair/dockeri:latest
  volumes:
  - name: cache
    path: /mi
  - name: docker-sock
    path: /var/run/docker.sock
  commands:
  - cd /mi
  - git clone https://github.com/qpzxcv4869/AutoMihoyoBBS
  - cd Auto*
  - docker build -t chaikair/test:1 .
# 部署

steps:
- name: 自动部署
  image: appleboy/drone-ssh
  settings:
    host: 
      - 47.242.239.1
    username: root
    password: 4sTHjq0QfVj8
    port: 22
    command_timeout: 5m
    script:
      - docker run --name mihoyobbsv1 -d chaikair/test:1
# 声明储存
volumes:
- name: cache
  temp: {}
- name: docker-sock
  host:
   path: /var/run/docker.sock
