kind: pipeline
type: docker
name: 米游社签到
steps:
node:
  server: USA
clone:
  disable: true
steps:
- name: 自动构建
  image: chaikair/dockeri:latest
  volumes:
  - name: cache
    path: /mi
  - name: docker-sock
    path: /var/run/docker.sock
  commands:
  - apk add git
  - cd /mi
  - git clone https://github.com/qpzxcv4869/AutoMihoyoBBS
  - cd Auto*
  - docker build -t chaikair/test:1 .
# 部署
- name: 自动部署
  image: chaikair/dockeri:latest
  volumes:
  - name: docker-sock
    path: /var/run/docker.sock
  commands:
  - docker run --name mihoyobbsv1 -d chaikair/test:1
# 声明储存
volumes:
- name: cache
  temp: {}
- name: docker-sock
  host:
   path: /var/run/docker.sock
